# Stubs for django.contrib.sites.management (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.apps import apps as global_apps

def create_default_site(app_config, verbosity: int = ..., interactive: bool = ..., using: Any = ..., apps: Any = ..., **kwargs): ...
