# Stubs for django.contrib.sites.middleware (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.deprecation import MiddlewareMixin
from .shortcuts import get_current_site as get_current_site

class CurrentSiteMiddleware(MiddlewareMixin):
    def process_request(self, request): ...
