# Stubs for django.core.checks.compatibility.django_1_10 (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def check_duplicate_middleware_settings(app_configs, **kwargs): ...
