# Stubs for django.urls.exceptions (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.http import Http404

class Resolver404(Http404): ...
class NoReverseMatch(Exception): ...
