# Stubs for django.middleware.cache (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from django.utils.deprecation import MiddlewareMixin

class UpdateCacheMiddleware(MiddlewareMixin):
    cache_timeout = ...  # type: Any
    key_prefix = ...  # type: Any
    cache_alias = ...  # type: Any
    cache = ...  # type: Any
    get_response = ...  # type: Any
    def __init__(self, get_response: Optional[Any] = ...) -> None: ...
    def process_response(self, request, response): ...

class FetchFromCacheMiddleware(MiddlewareMixin):
    key_prefix = ...  # type: Any
    cache_alias = ...  # type: Any
    cache = ...  # type: Any
    get_response = ...  # type: Any
    def __init__(self, get_response: Optional[Any] = ...) -> None: ...
    def process_request(self, request): ...

class CacheMiddleware(UpdateCacheMiddleware, FetchFromCacheMiddleware):
    get_response = ...  # type: Any
    key_prefix = ...  # type: Any
    cache_alias = ...  # type: Any
    cache_timeout = ...  # type: Any
    cache = ...  # type: Any
    def __init__(self, get_response: Optional[Any] = ..., cache_timeout: Optional[Any] = ..., **kwargs) -> None: ...
