# Stubs for django.middleware.csrf (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.utils.deprecation import MiddlewareMixin

logger = ...  # type: Any
REASON_NO_REFERER = ...  # type: str
REASON_BAD_REFERER = ...  # type: str
REASON_NO_CSRF_COOKIE = ...  # type: str
REASON_BAD_TOKEN = ...  # type: str
REASON_MALFORMED_REFERER = ...  # type: str
REASON_INSECURE_REFERER = ...  # type: str
CSRF_SECRET_LENGTH = ...  # type: int
CSRF_TOKEN_LENGTH = ...  # type: Any
CSRF_ALLOWED_CHARS = ...  # type: Any

def get_token(request): ...
def rotate_token(request): ...

class CsrfViewMiddleware(MiddlewareMixin):
    def process_view(self, request, callback, callback_args, callback_kwargs): ...
    def process_response(self, request, response): ...
