# Stubs for django.middleware.locale (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.utils.deprecation import MiddlewareMixin

class LocaleMiddleware(MiddlewareMixin):
    response_redirect_class = ...  # type: Any
    def process_request(self, request): ...
    def process_response(self, request, response): ...
