# Stubs for django.views.csrf (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.utils.translation import ugettext as _

CSRF_FAILURE_TEMPLATE = ...  # type: str
CSRF_FAILURE_TEMPLATE_NAME = ...  # type: str

def csrf_failure(request, reason: str = ..., template_name: Any = ...): ...
