# Stubs for django.views.defaults (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

ERROR_404_TEMPLATE_NAME = ...  # type: str
ERROR_403_TEMPLATE_NAME = ...  # type: str
ERROR_400_TEMPLATE_NAME = ...  # type: str
ERROR_500_TEMPLATE_NAME = ...  # type: str

def page_not_found(request, exception, template_name: Any = ...): ...
def server_error(request, template_name: Any = ...): ...
def bad_request(request, exception, template_name: Any = ...): ...
def permission_denied(request, exception, template_name: Any = ...): ...
