# Stubs for django.template.loader (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from .base import Origin as Origin
from .exceptions import TemplateDoesNotExist as TemplateDoesNotExist

def get_template(template_name, using: Optional[Any] = ...): ...
def select_template(template_name_list, using: Optional[Any] = ...): ...
def render_to_string(template_name, context: Optional[Any] = ..., request: Optional[Any] = ..., using: Optional[Any] = ...): ...

class LoaderOrigin:
    alternative = ...  # type: str
    deprecation_warning = ...  # type: Any
