# Stubs for django.contrib.sessions.exceptions (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.core.exceptions import SuspiciousOperation

class InvalidSessionKey(SuspiciousOperation): ...
class SuspiciousSession(SuspiciousOperation): ...
