# Stubs for django.contrib.gis.geometry.regex (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

hex_regex = ...  # type: Any
wkt_regex = ...  # type: Any
json_regex = ...  # type: Any
