# Stubs for django.db.models (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.models.aggregates import *
from django.db.models.fields import *

def permalink(func): ...
