# Stubs for django.db.models.signals (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from django.dispatch import Signal

class_prepared = ...  # type: Any

class ModelSignal(Signal):
    def connect(self, receiver, sender: Optional[Any] = ..., weak: bool = ..., dispatch_uid: Optional[Any] = ..., apps: Optional[Any] = ...): ...
    def disconnect(self, receiver: Optional[Any] = ..., sender: Optional[Any] = ..., weak: Optional[Any] = ..., dispatch_uid: Optional[Any] = ..., apps: Optional[Any] = ...): ...

pre_init = ...  # type: Any
post_init = ...  # type: Any
pre_save = ...  # type: Any
post_save = ...  # type: Any
pre_delete = ...  # type: Any
post_delete = ...  # type: Any
m2m_changed = ...  # type: Any
pre_migrate = ...  # type: Any
post_migrate = ...  # type: Any
