# Stubs for django.contrib.staticfiles.templatetags.staticfiles (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.templatetags.static import do_static as _do_static, static as _static

register = ...  # type: Any

def static(path): ...
def do_static(parser, token): ...
