# Stubs for django.test.selenium (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class SeleniumTestCaseBase:
    browsers = ...  # type: Any
    browser = ...  # type: Any
    def __new__(cls, name, bases, attrs): ...
    @classmethod
    def import_webdriver(cls, browser): ...
    def create_webdriver(self): ...

class SeleniumTestCase:
    implicit_wait = ...  # type: int
    @classmethod
    def setUpClass(cls): ...
    def disable_implicit_wait(self): ...
