# Stubs for django.contrib.gis.gdal.base (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class GDALBase:
    ptr_type = ...  # type: Any
    ptr = ...  # type: Any
