# Stubs for django.conf.urls.i18n (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def i18n_patterns(*urls, **kwargs): ...
def is_language_prefix_patterns_used(urlconf): ...

urlpatterns = ...  # type: Any
