# Stubs for django.contrib.auth.apps (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.apps import AppConfig
from django.utils.translation import ugettext_lazy as _
from .checks import check_models_permissions as check_models_permissions, check_user_model as check_user_model
from .management import create_permissions as create_permissions

class AuthConfig(AppConfig):
    name = ...  # type: str
    verbose_name = ...  # type: Any
    def ready(self): ...
