# Stubs for django.contrib.auth.validators (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.core import validators
from django.utils.translation import ugettext_lazy as _

class ASCIIUsernameValidator(validators.RegexValidator):
    regex = ...  # type: str
    message = ...  # type: Any
    flags = ...  # type: Any

class UnicodeUsernameValidator(validators.RegexValidator):
    regex = ...  # type: str
    message = ...  # type: Any
    flags = ...  # type: Any
