# Stubs for django.http.cookie (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import sys
from typing import Any
from six.moves import http_cookies

cookie_pickles_properly = ...  # type: bool

if sys.version_info >= (3, 4, 3):
	SimpleCookie = http_cookies.SimpleCookie
else:
	Morsel = http_cookies.Morsel  # type: ignore
	
	class SimpleCookie(http_cookies.SimpleCookie):  # type: ignore
		def __setitem__(self, key, value): ...
		bad_cookies = ...  # type: Any
		def load(self, rawdata): ...

def parse_cookie(cookie): ...
