# Stubs for django.contrib.auth.management (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.apps import apps as global_apps

def create_permissions(app_config, verbosity: int = ..., interactive: bool = ..., using: Any = ..., apps: Any = ..., **kwargs): ...
def get_system_username(): ...
def get_default_username(check_db: bool = ...): ...
