# Stubs for django.core.mail.backends.locmem (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.core.mail.backends.base import BaseEmailBackend

class EmailBackend(BaseEmailBackend):
    def __init__(self, *args, **kwargs) -> None: ...
    def send_messages(self, messages): ...
