# Stubs for django.utils.html_parser (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.utils.six.moves import html_parser as _html_parser
import _html_parser

HTMLParseError = ...  # type: Any

class HTMLParseError(Exception): ...

class HTMLParser(_html_parser.HTMLParser):
    def __init__(self, convert_charrefs: bool = ..., **kwargs) -> None: ...

HTMLParser = ...  # type: Any
