# Stubs for django.utils.html_parser (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import sys
from typing import Any
from django.utils.six.moves import html_parser as _html_parser

if sys.version_info[0] >= 3:
	class HTMLParseError(Exception): ...
	
	class HTMLParser(_html_parser.HTMLParser):
	    def __init__(self, convert_charrefs: bool = ..., **kwargs) -> None: ...
else:	
	HTMLParseError = _html_parser.HTMLParserError
	HTMLParser = _html_parser.HTMLParser
