# Stubs for django (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

VERSION = ...  # type: Any

def setup(set_prefix: bool = ...): ...
