# Stubs for django.contrib.gis.db.backends.spatialite.adapter (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.contrib.gis.db.backends.base.adapter import WKTAdapter

class SpatiaLiteAdapter(WKTAdapter):
    def __conform__(self, protocol): ...
