# Stubs for django.contrib.admindocs.middleware (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.deprecation import MiddlewareMixin

class XViewMiddleware(MiddlewareMixin):
    def process_view(self, request, view_func, view_args, view_kwargs): ...
