# Stubs for django.conf.locale.mn.formats (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

DATE_FORMAT = ...  # type: str
TIME_FORMAT = ...  # type: str
SHORT_DATE_FORMAT = ...  # type: str
