# Stubs for django.contrib.gis.geos.prototypes (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.contrib.gis.geos.prototypes.misc import *
from django.contrib.gis.geos.prototypes.topology import *
