# Stubs for django.contrib.gis.geos.prototypes.io (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
import threading
from ctypes import Structure
from django.contrib.gis.geos.base import GEOSBase
from django.contrib.gis.geos.libgeos import GEOSFuncFactory

class WKTReader_st(Structure): ...
class WKTWriter_st(Structure): ...
class WKBReader_st(Structure): ...
class WKBWriter_st(Structure): ...

WKT_READ_PTR = ...  # type: Any
WKT_WRITE_PTR = ...  # type: Any
WKB_READ_PTR = ...  # type: Any
WKB_WRITE_PTR = ...  # type: Any
wkt_reader_create = ...  # type: Any
wkt_reader_destroy = ...  # type: Any
wkt_reader_read = ...  # type: Any
wkt_writer_create = ...  # type: Any
wkt_writer_destroy = ...  # type: Any
wkt_writer_write = ...  # type: Any
wkt_writer_get_outdim = ...  # type: Any
wkt_writer_set_outdim = ...  # type: Any
wkt_writer_set_trim = ...  # type: Any
wkt_writer_set_precision = ...  # type: Any
wkb_reader_create = ...  # type: Any
wkb_reader_destroy = ...  # type: Any

class WKBReadFunc(GEOSFuncFactory):
    argtypes = ...  # type: Any
    restype = ...  # type: Any
    errcheck = ...  # type: Any

wkb_reader_read = ...  # type: Any
wkb_reader_read_hex = ...  # type: Any
wkb_writer_create = ...  # type: Any
wkb_writer_destroy = ...  # type: Any

class WKBWriteFunc(GEOSFuncFactory):
    argtypes = ...  # type: Any
    restype = ...  # type: Any
    errcheck = ...  # type: Any

wkb_writer_write = ...  # type: Any
wkb_writer_write_hex = ...  # type: Any

class WKBWriterGet(GEOSFuncFactory):
    argtypes = ...  # type: Any
    restype = ...  # type: Any

class WKBWriterSet(GEOSFuncFactory):
    argtypes = ...  # type: Any

wkb_writer_get_byteorder = ...  # type: Any
wkb_writer_set_byteorder = ...  # type: Any
wkb_writer_get_outdim = ...  # type: Any
wkb_writer_set_outdim = ...  # type: Any
wkb_writer_get_include_srid = ...  # type: Any
wkb_writer_set_include_srid = ...  # type: Any

class IOBase(GEOSBase):
    ptr = ...  # type: Any
    def __init__(self) -> None: ...
    def __del__(self): ...

class _WKTReader(IOBase):
    ptr_type = ...  # type: Any
    def read(self, wkt): ...

class _WKBReader(IOBase):
    ptr_type = ...  # type: Any
    def read(self, wkb): ...

class WKTWriter(IOBase):
    ptr_type = ...  # type: Any
    trim = ...  # type: Any
    precision = ...  # type: Any
    outdim = ...  # type: Any
    def __init__(self, dim: int = ..., trim: bool = ..., precision: Optional[Any] = ...) -> None: ...
    def write(self, geom): ...
    @property
    def outdim(self): ...
    @outdim.setter
    def outdim(self, new_dim): ...
    @property
    def trim(self): ...
    @trim.setter
    def trim(self, flag): ...
    @property
    def precision(self): ...
    @precision.setter
    def precision(self, precision): ...

class WKBWriter(IOBase):
    ptr_type = ...  # type: Any
    outdim = ...  # type: Any
    def __init__(self, dim: int = ...) -> None: ...
    def write(self, geom): ...
    def write_hex(self, geom): ...
    byteorder = ...  # type: Any
    @property
    def outdim(self): ...
    @outdim.setter
    def outdim(self, new_dim): ...
    @property
    def srid(self): ...
    @srid.setter
    def srid(self, include): ...

class ThreadLocalIO(threading.local):
    wkt_r = ...  # type: Any
    wkt_w = ...  # type: Any
    wkb_r = ...  # type: Any
    wkb_w = ...  # type: Any
    ewkb_w = ...  # type: Any

thread_context = ...  # type: Any

def wkt_r(): ...
def wkt_w(dim: int = ..., trim: bool = ..., precision: Optional[Any] = ...): ...
def wkb_r(): ...
def wkb_w(dim: int = ...): ...
def ewkb_w(dim: int = ...): ...
