# Stubs for django.core.management.commands.flush (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.core.management.base import BaseCommand

class Command(BaseCommand):
    help = ...  # type: str
    def add_arguments(self, parser): ...
    style = ...  # type: Any
    def handle(self, **options): ...
