# Stubs for django.contrib.contenttypes.checks (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def check_generic_foreign_keys(app_configs: Optional[Any] = ..., **kwargs): ...
