# Stubs for django.contrib.contenttypes.management (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
import migrations
from django.apps import apps as global_apps

class RenameContentType(migrations.RunPython):
    app_label = ...  # type: Any
    old_model = ...  # type: Any
    new_model = ...  # type: Any
    def __init__(self, app_label, old_model, new_model) -> None: ...
    def rename_forward(self, apps, schema_editor): ...
    def rename_backward(self, apps, schema_editor): ...

def inject_rename_contenttypes_operations(plan: Optional[Any] = ..., apps: Any = ..., using: Any = ..., **kwargs): ...
def update_contenttypes(app_config, verbosity: int = ..., interactive: bool = ..., using: Any = ..., apps: Any = ..., **kwargs): ...
